FROM docker.io/debian:stable-slim

# Install Software
RUN apt-get update; apt-get install -y curl git python3 pip gcc g++ gdb valgrind cmake rust-all

# Copy configs and runscript
COPY opencode.json /root/.config/opencode/opencode.json

# Install opencode
RUN curl -fsSL https://opencode.ai/install | bash

WORKDIR /app
CMD ["/root/.opencode/bin/opencode"]

