FROM docker.io/ollama/ollama
WORKDIR /opt/

# Install dependencies
RUN apt-get update
RUN apt-get install -y curl

# Install claude-code
RUN curl -fSLO https://claude.ai/install.sh
RUN bash install.sh
RUN rm install.sh
RUN echo 'export PATH="$HOME/.local/bin:$PATH"' >> '/root/.bashrc'

# Install OpenCode
RUN curl -fSLO https://opencode.ai/install
RUN bash install
RUN rm install

